export const ROUTES = {
  home: "/",
  shop: "/shop",
  category: (slug: string) => `/category/${slug}`,
  product: (slug: string) => `/product/${slug}`,
  search: "/search",
  cart: "/cart",
  checkout: "/checkout",
  wishlist: "/wishlist",
  about: "/about",
  contact: "/contact",
  faq: "/faq",
  shippingPolicy: "/shipping-policy",
  returnRefund: "/return-refund",
  cancellation: "/cancellation",
  privacyPolicy: "/privacy-policy",
  terms: "/terms",
  grievance: "/grievance-redressal",
  account: {
    root: "/account",
    orders: "/account/orders",
    order: (orderNumber: string) => `/account/orders/${orderNumber}`,
    addresses: "/account/addresses",
    profile: "/account/profile",
  },
  auth: {
    login: "/login",
    register: "/register",
    verifyOtp: "/verify-otp",
    forgotPassword: "/forgot-password",
  },
  admin: {
    login: "/admin/login",
    dashboard: "/admin",
    products: "/admin/products",
    categories: "/admin/categories",
    brands: "/admin/brands",
    inventory: "/admin/inventory",
    orders: "/admin/orders",
    customers: "/admin/customers",
    payments: "/admin/payments",
    returns: "/admin/returns",
    refunds: "/admin/refunds",
    coupons: "/admin/coupons",
    reviews: "/admin/reviews",
    reports: "/admin/reports",
    settings: "/admin/settings",
  },
} as const;
